/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntesEDepoisRouteImport } from './routes/antes-e-depois'
import { Route as BijuteriasRouteImport } from './routes/bijuterias'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProcedimentosSlugRouteImport } from './routes/procedimentos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntesEDepoisRoute = AntesEDepoisRouteImport.update({
  id: '/antes-e-depois',
  path: '/antes-e-depois',
  getParentRoute: () => rootRouteImport,
} as any)
const BijuteriasRoute = BijuteriasRouteImport.update({
  id: '/bijuterias',
  path: '/bijuterias',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosSlugRoute = ProcedimentosSlugRouteImport.update({
  id: '/procedimentos/$slug',
  path: '/procedimentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antes-e-depois': typeof AntesEDepoisRoute
  '/bijuterias': typeof BijuteriasRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/faq': typeof FaqRoute
  '/sobre': typeof SobreRoute
  '/procedimentos/$slug': typeof ProcedimentosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antes-e-depois': typeof AntesEDepoisRoute
  '/bijuterias': typeof BijuteriasRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/faq': typeof FaqRoute
  '/sobre': typeof SobreRoute
  '/procedimentos/$slug': typeof ProcedimentosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antes-e-depois': typeof AntesEDepoisRoute
  '/bijuterias': typeof BijuteriasRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/faq': typeof FaqRoute
  '/sobre': typeof SobreRoute
  '/procedimentos/$slug': typeof ProcedimentosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antes-e-depois'
    | '/bijuterias'
    | '/carrinho'
    | '/catalogo'
    | '/contato'
    | '/depoimentos'
    | '/faq'
    | '/sobre'
    | '/procedimentos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antes-e-depois'
    | '/bijuterias'
    | '/carrinho'
    | '/catalogo'
    | '/contato'
    | '/depoimentos'
    | '/faq'
    | '/sobre'
    | '/procedimentos/$slug'
  id:
    | '__root__'
    | '/'
    | '/antes-e-depois'
    | '/bijuterias'
    | '/carrinho'
    | '/catalogo'
    | '/contato'
    | '/depoimentos'
    | '/faq'
    | '/sobre'
    | '/procedimentos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntesEDepoisRoute: typeof AntesEDepoisRoute
  BijuteriasRoute: typeof BijuteriasRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  ContatoRoute: typeof ContatoRoute
  DepoimentosRoute: typeof DepoimentosRoute
  FaqRoute: typeof FaqRoute
  SobreRoute: typeof SobreRoute
  ProcedimentosSlugRoute: typeof ProcedimentosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antes-e-depois': {
      id: '/antes-e-depois'
      path: '/antes-e-depois'
      fullPath: '/antes-e-depois'
      preLoaderRoute: typeof AntesEDepoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bijuterias': {
      id: '/bijuterias'
      path: '/bijuterias'
      fullPath: '/bijuterias'
      preLoaderRoute: typeof BijuteriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos/$slug': {
      id: '/procedimentos/$slug'
      path: '/procedimentos/$slug'
      fullPath: '/procedimentos/$slug'
      preLoaderRoute: typeof ProcedimentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntesEDepoisRoute: AntesEDepoisRoute,
  BijuteriasRoute: BijuteriasRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  ContatoRoute: ContatoRoute,
  DepoimentosRoute: DepoimentosRoute,
  FaqRoute: FaqRoute,
  SobreRoute: SobreRoute,
  ProcedimentosSlugRoute: ProcedimentosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
